services:
  - type: web
    name: tractonow
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r backend/requirements.txt && cd backend && python models/train_model.py && python database/seed.py"
    startCommand: "gunicorn --chdir backend 'app:create_app()' --workers 2 --timeout 120 --bind 0.0.0.0:$PORT"
    envVars:
      - key: MONGO_URI
        sync: false          # set manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true  # Render auto-generates a secure value
      - key: JWT_EXPIRY
        value: 604800
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.9"
